services:
    # postgres:
    #     image: postgres:18-alpine
    #     container_name: gym_app_db
    #     environment:
    #         POSTGRES_USER: ${DB_USER}
    #         POSTGRES_PASSWORD: ${DB_PASS}
    #         POSTGRES_DB: ${DB_NAME}
    #     ports:
    #         - "5432:5432"
    #     volumes:
    #         - postgres_data:/var/lib/postgresql/data
    #     healthcheck:
    #         test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    backend:
        build:
            context: ./backend
            args:
                API_URL: ${API_URL}
        image: gym_app/backend:v1
        container_name: gym_app_backend
        env_file:
            - .env
        ports:
            - "3001:3001"
        # depends_on:
        #     postgres:
        #         condition: service_healthy
        environment:
            PORT: ":3001"
            DB_HOST: postgres
            DB_PORT: "5432"
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_NAME: ${DB_NAME}
# volumes:
#     postgres_data:
