// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID     int64
	Name   interface{}
	Dob    pgtype.Date
	Joined pgtype.Date
}
